version: '3.8'
services:
  # 开发环境
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weektodo-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 生产环境
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: weektodo-prod
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules:
